global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'ems'
    metrics_path: '/ems/actuator/prometheus'
    static_configs:
      - targets: ['ems:8083'] ##ems app url